apiVersion: v1
kind: Service
metadata:
  #Cambiame:
  name: teagile-zuul-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: 8080-tcp

  #Ojo con los selectores, deben coincidir con los "labels" del deployment"
  #Cambiame:
  selector:
    app: teagile-zuul-service
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
#Cambiame:
metadata:
  name: teagile-zuul-service-deployment
spec:
  selector:
    matchLabels:
      #Cambiame:
      app: teagile-zuul-service
      tier: backend
  template:
    metadata:

      #Ojo con los selectores, deben coincidir con los "labels" del service"
      #Cambiame:
      labels:
        app: teagile-zuul-service
        tier: backend
    spec:
      imagePullSecrets:
      - name: docker-registry-innersource
      containers:
      #Cambiame:
      - image: registry-innersource.soprasteria.com/smartup/sopra-profile/teagile-zuul-service:develop
        name: teagile-zuul-service
        imagePullPolicy: Always
        env:
          - name: SERVER_PORT
            value: 8080
          - name: ZUUL_ROUTES_HANDLEMOVIES-SERVICE_URL
            value: teagile-core-service.apps.12b5129e45db47179d12.westeurope.aksapp.io

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #Cambiame:
  name: teagile-zuul-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  #Cambiame: (solo la parte de antes de .apps.12b...)
  - host: teagile-zuul-service.apps.12b5129e45db47179d12.westeurope.aksapp.io
    http:
      paths:
      #Cambiame:
      - backend:
          #Cambiame:
          #Ojo!... Tiene que coincidir con el nombre del servicio.
          serviceName: teagile-zuul-service
          servicePort: 8080
